### ISSUE TITLE
Filename is too long while cloning repository in windows

### ISSUE THREAD

**Issue by nagnagendra** [microsoftgraph/msgraph-sdk-go-core#47]
**go get -u github.com/microsoftgraph/msgraph-sdk-go-core**

error: unable to create file msgraph-mail/java/utilities/src/main/java/graphjavav4/utilities/users/item/mailFolders/item/messages/item/multiValueExtendedProperties/item/MultiValueLegacyExtendedPropertyRequestBuilder.java: Filename too long
error: unable to create file msgraph-mail/java/utilities/src/main/java/graphjavav4/utilities/users/item/mailFolders/item/messages/item/singleValueExtendedProperties/item/SingleValueLegacyExtendedPropertyRequestBuilder.java: Filename too long
Unable to checkout 'b42e1a879cf62da7e666dcf38d4ab69357abba1d' in submodule path 'samples'****

Please provide alternative way to do this in windows platform.

**Comment by baywet** [comment]
Hi @nagnagendra 
Thanks for trying out the SDK and for reaching out.

This is caused because the SDK depends on libraries that live in [kiota](https://github.com/microsoft/kiota), the generator used for this SDK, and this repo has a submodule linked to the samples repo. During the dependency resolution process, the Go package manager which depends on Git, also clones that submodule.

What's the path of your repo on disk? using a shorter root path should work around this issue.

Alternatively, you can enable long paths support on your system, [see this](https://www.tenforums.com/tutorials/51704-enable-disable-win32-long-paths-windows-10-a.html) (option 2, registry)

As we move towards the GA of the SDK we have a plan to move those dependencies onto their own dedicated repository which should solve this issue, see https://github.com/microsoft/kiota/issues/370

I've also [issued a pull request to remove the submodule](https://github.com/microsoft/kiota/pull/1199) and make the update of the packages faster/easier.

**Comment by baywet** [comment]
Closing since https://github.com/microsoft/kiota/pull/1199 has been merged and the reference has been updated.
